### ISSUE TITLE
Program in disorder! trying to force stuck pet down stairs

### ISSUE THREAD

**Issue by tux3** [copperwater/xNetHack#108]
My Barbarian tried in vain to get Idefix to follow down to Dlvl 2. The pet could move, and could stay near me, but would not come down despite repeated attempts.
Having failed, I went to the mines alone and found a leash. A level teleport trap sent me back up.

I tamed my now feral pet again, applied a leash, buc tested a few things, and tried to go down stairs again.  
Pet's attachment to Dlvl 1 was evidently stronger than my leash, and I received this message:

>leash in use isn't attached to anything?  Program in disorder!  (Saving and reloading may fix this problem.)

If I go back up to Dlvl 1, I see `tame little dog called Idefix, leashed to you`.
If I go back down again, I no longer get the message though my pet remains upstairs.

This is running `32b859ac8 Pre-release addition of flavor text strings for 8.0` built with stock `sys/unix/hints/linux.370`.

Here's a core file, standing on the downstairs next to the pet: 
[core.566911.remove.this.txt](https://github.com/copperwater/xNetHack/files/11496290/core.566911.remove.this.txt)

Edit: After saving and reloading, the problem persists. I dropped the leash from my inventory. The dog picked up and dropped the leash. Farlook says "tame little dog called Idefix, fleeing, leashed to you" despite the leash being on the ground (I suppose that might just be fallout from the disorder of the leash in use coming unattached?).

**Comment by tux3** [comment]
Not sure if relevant, but I had done the tutorial this session. I wonder if going to the tutorial and back could have messed up the pet?

**Comment by copperwater** [comment]
Confirmed this is a vanilla bug. When you play the tutorial, reenter the dungeon, and subsequently try to take your pets down stairs, `keepdogs()` is not getting called because the `u.nofollowers` flag is incorrectly set (it is supposed to be set only when entering the tutorial).

Reported this as https://github.com/NetHack/NetHack/issues/1027.

Workaround is to not do the tutorial. (I suppose, if one is playing petless, then this is actually a boon, since it will buggily prevent other monsters from following you as well when you want to escape a level).

**Comment by copperwater** [comment]
This should be resolved as of the vanilla merge I did earlier today.
