### ISSUE TITLE
"mazewalk unfinished? stone at <2,2>" descending stair from Medusa, then collapse

### ISSUE THREAD

**Issue by tux3** [copperwater/xNetHack#109]
I'm not sure that I did anything out of the ordinary this time, but taking the stairs down after defeating Medusa resulted in this `mazewalk unfinished? stone at <2,2>` message:

![snap-1212](https://github.com/copperwater/xNetHack/assets/5155966/cba586f9-0d15-4cca-91d3-c13414c538f8)

Then,

```
Suddenly, the dungeon collapses.
To report this error, Contact K2 or Tangles on irc.libera.chat channel #hardfought
and it may be possible to rebuild.

mazexy: can't find a place!
```

In case that helps any, here's a core dump from just before the collapse: [core.632359.remove.this.txt](https://github.com/copperwater/xNetHack/files/11511677/core.632359.remove.this.txt)

And a tarball of ~/nh/install/games: [nh-games.tar.gz](https://github.com/copperwater/xNetHack/files/11511702/nh-games.tar.gz)

**Comment by copperwater** [comment]
This happens reliably when a maze tries to generate below Medusa's level. As such, the only way to complete the game without crashing it is happening to only generate regular dungeon levels between Medusa and the Castle or having Medusa generate adjacent to the castle. Since this makes it practically unwinnable for anyone downloading the windows binary, I am going to withdraw the release and move 8.0 back to beta status.

In the meantime, I'm not planning to fix the actual bug at fault here - instead I will take the opportunity to eradicate mazes that generate by default (i.e. not with des.mazewalk specifically requested in a lua file like the Catacombs). Levels below Medusa will always be room-and-corridor, and a level that fails to load will instead use an empty expanse as its default case.

**Comment by tux3** [comment]
Thank you, that was enough to recover my save!  
I respawned in a blank void, but conjuring a fake staircase up in memory seems to have worked!

![snap-1214](https://github.com/copperwater/xNetHack/assets/5155966/3bfca786-bad9-410d-a877-13ddf86f0758)

Then I commented out maze generation below mesuda like you suggested, erased the broken Dlvl 24, and mklev did let me continue with a room-and-corridor without problems

```
src/mklev.c
@@ -1246,8 +1246,8 @@ makelevel(void)
                 (u.uz.dlevel < loc_lev->dlevel.dlevel) ? "a" : "b");
         makemaz(fillname);
     } else if (In_hell(&u.uz)
-                || (rn2(5) && u.uz.dnum == medusa_level.dnum
-                    && depth(&u.uz) > depth(&medusa_level))) {
+                /*|| (rn2(5) && u.uz.dnum == medusa_level.dnum
+                    && depth(&u.uz) > depth(&medusa_level))*/) {
```

Now to ruin the rest of this save on my own, here we go.. =)

**Comment by copperwater** [comment]
As of now, random mazes have been removed from the game, so this error should no longer occur.
