### ISSUE TITLE
No portal on the Plane of Air

### ISSUE THREAD

**Issue by Ardub23** [copperwater/xNetHack#183]
I'm playing on the Hardfought US server. Upon stepping on the portal leading from Earth to Air, an impossible() message "portal on top of portal?" appeared, followed by "set_wportal(): no portal!". The latter message recurred every turn or so as I got out a scroll of gold detection to confused-read, which confirmed that there were no traps on the level.

I can't think of anything unusual that happened leading up to this that might have caused it. I have no idea if this bug comes from vanilla, but it's troubling to say the least.

Here's the ttyrec from the session where I encountered this: [2023-06-10.05_01_42.ttyrec.gz](https://github.com/copperwater/xNetHack/files/11713693/2023-06-10.05_01_42.ttyrec.gz)

**Comment by copperwater** [comment]
According to K2, this happened on an 8.0 beta game (not the release at the end of May), and is due to a vanilla bug that the beta release's last vanilla merge had just barely not picked up the fix for: https://github.com/NetHack/NetHack/commit/e28d15f4915e2f41d9c340957662ec37ac5d2a39

The formal 8.0 release merged in vanilla again and picked up this commit, so it doesn't have this problem, but unfortunately, you can't advance your particular game beyond Air. My apologies.
