### ISSUE TITLE
I can't get this to compile no matter what I try. 

### ISSUE THREAD

**Issue by Razoozle** [copperwater/xNetHack#28]
Visual Studio keeps giving me this error, and I'm not very familiar with compiling source code. The instructions are very confusing. Can somebody pre-compile this? I'd love to play offline.

error : Your project does not reference ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.

**Comment by copperwater** [comment]
I'm working on getting Windows binaries building automatically. Here's a recent test build you can download if you want (not the 6.0 release, but basically has all the same code because I'm very close to releasing 6.0): https://github.com/copperwater/xNetHack/releases/tag/test-22

The process of getting the Windows build to work may have also fixed whatever problem you were having with compiling xNetHack.

**Comment by Razoozle** [comment]
Awesome! Thank you!

**Comment by copperwater** [comment]
Assuming that the problem has been fixed.
