### ISSUE TITLE
Redesign Curses interface to force it align the popup menus to the center

### ISSUE THREAD

**Issue by Terrarian51** [copperwater/xNetHack#43]
The Curses interface is tend to place the pop-ups to the right part, But, for me, it looks ugly... Is this possible to re-align the popup menus to the center, just like DynaHack developer did?

**Comment by copperwater** [comment]
Pull requests to address this will be happily accepted, however...

I can tell you that messing with the curses interface code is such a low priority that it is unlikely to ever happen in xNetHack work. Whether DynaHack did it already is irrelevant since its curses interface is derived from NitroHack, which is almost completely different in terms of code from the curses interface added to vanilla 3.6.

Furthermore this is not a bug introduced by xNetHack, it is a complaint about vanilla. I recommend taking that complaint to the devteam and seeing if they address it.
