### ISSUE TITLE
Dump log inconsistencies

### ISSUE THREAD

**Issue by Graznop** [copperwater/xNetHack#46]
In a recent game, the achievement "You completed the Gnomish Mines" was not recorded in the end game log.
It appears to have been replaced by a "You handled the Bell of Opening" message (this appears twice).
The Mines' End variant was the Gnomish Sewer.

Dump log:
https://eu.hardfought.org/userdata/G/Graznop/xnethack/dumplog/1623968162.xnh.html

Acquiring the Mines' End luckstone was noted by Beholder on IRC (at 09:00), just before attaining the rank of Exhumer (at 09:05):
https://www.hardfought.org/irclog/%23hardfought-2021-06-19.log

**Comment by actual-nh** [comment]
At least in the HTML version of the dumplog, there are also some (formatting only as far as I can tell) difficulties with the transition between the last part before the dungeon description (achievements or otherwise):
```
* You ascended!
* The Elemental Planes:
* Astral Plane: <- You are here.
```
This is visible in the one above from Graznop, in <https://www.hardfought.org/userdata/B/Bartlem/xnethack/dumplog/1623080099.xnh.html>, and in <https://eu.hardfought.org/userdata/F/FIQ/xnethack/dumplog/1624035205.xnh.html>. Two not ascensions:
* With achievements: <https://eu.hardfought.org/userdata/w/wheals/xnethack/dumplog/1624229124.xnh.html>
* Without achievements: <https://www.hardfought.org/userdata/L/Luxidream/xnethack/dumplog/1624223950.xnh.html>

> In a recent game, the achievement "You completed the Gnomish Mines" was not recorded in the end game log. It appears to have been replaced by a "You handled the Bell of Opening" message (this appears twice).

Will have to check if completing the Gnomish Mines is recorded correctly in the xlogfile.

**Comment by copperwater** [comment]
Appears to have been fixed at some point, since when I tested locally (I teleported to mines' end, picked up the luckstone, wished for the Bell of Opening, then quit) my dumplog says "You completed the Gnomish Mines. You had the Bell of Opening."

Please reopen if you're still experiencing this.
