### ISSUE TITLE
Feedback on new Valkyrie quest

### ISSUE THREAD

**Issue by gregorp** [copperwater/xNetHack#90]
Hey there--I'm not sure if this is an appropriate forum for general feedback--let me know if there's somewhere you'd prefer I post this.

I'm playing on Hardfought for the first time in a year or so with no idea that I was on a new xNetHack version. I was delighted when I realized the Valkyrie quest was overhauled. The new Home level is much more interesting, and the Bifrost is very cool. Overall I love it.

I have one complaint, and that's anti-synergy of the Sol Valtiva with my other weapon options. I started with the +1 Spear, took a little while to find a long sword and then #dipped for Excalibur. Eventually I found a convertible altar and sacrificed for Mjolnir, and then went on the Quest, where I was surprised to pick up Sol Valtiva. So I have 3 great weapon options. Sol Valtiva, dealing fire damage and being 2-handed seems like a sub-optimal choice for Gehennom. It's really cool that it acts as a light source, but I mostly want a light source for throwing Mjolnir, and it won't work for that because I'd need to wield both of them. So while I'm psyched for a new artifact, I'm a little disappointed that I'll probably not use it much.

When I play a Valkyrie, I love wielding Mjolnir. It seems super-thematic. I like the way it's beefed up in xNetHack with the new #invoke ability and I don't mind the risky two-handed trade-off for more damage. Maybe Mjolnir should just be the Valkyrie quest artifact? But it doesn't seem like Valks need a new weapon option.

Thanks for all your work!

**Comment by copperwater** [comment]
This is a better forum for feedback than posting on Reddit or emailing me, since it guarantees I will actually see it within a reasonable amount of time. The one drawback is that it's eventually going to get closed, which can make the original poster feel like they didn't accomplish anything.

So here's the thing: your feedback indicates that Sol Valtiva is actually working as intended. I bet that, while you didn't wield it much, *you still carried it around*, right? I was aiming to hit a sweet spot in which some Valkyries would not use the sword and others would -- those who have been unlucky with or can't get other artifacts, or dislike using Mjollnir because of its item destruction (in the upcoming version, Excalibur is not going to be something a Valkyrie can reasonably get pre-Quest) -- but the carry and invoke effects, deliberately similar to the Orb of Fate's most powerful effects, are still very much worth having. 

Another thing to keep in mind is that while Sol Valtiva is still technically the quest artifact for Valkyries, because I imagine only bad things would happen if I left a big hole in the quest artifacts array, it's not actually the object of the quest. As I said in the commit notes (46738ee7):

    One of the two major changes to the story is that Lord Surtur didn't steal
    any artifact from the home level. Instead, this is just his sword. You're
    under no particular compulsion to do anything with it, other than that it's
    a nice artifact to have. The goal of the quest is to kill him.

Which is itself part of the larger project to vary Quest stories from the tired old "the bad guy stole our shiny object, get the shiny object back for us" plot. True, this is one of the smaller departures from that, but more interesting stuff is planned for other roles.

**Comment by gregorp** [comment]
Thanks for the thoughtful reply.

I did end up carrying Sol Valtiva around and using it on most everything that wasn't fire-resistant. A permanent light source is a very big draw. And I ascended that run, so I suppose I should withdraw my complaints.

Thanks for all your work!
